version: "3.8"
services:
  github-state:
    container_name: github-state
    build: .
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      USER: ${GITHUB_USER_NAME}
      PAT_1: ${GITHUB_ACCESS_TOKEN}